import 'package:flutter/material.dart';

// Import the generated localizations
// These will be generated by flutter gen-l10n
export 'app_localizations.dart';

/// Locale metadata with font and script information
class KFLocaleInfo {
  final Locale locale;
  final String nativeName;
  final String englishName;
  final String? fontFamily;
  final TextDirection direction;
  final String flag;
  final String targetUsers;

  const KFLocaleInfo({
    required this.locale,
    required this.nativeName,
    required this.englishName,
    this.fontFamily,
    this.direction = TextDirection.ltr,
    required this.flag,
    required this.targetUsers,
  });
}

/// Production localization configuration for KerjaFlow
/// 12 ASEAN languages with proper font support
class KFL10n {
  KFL10n._();

  /// All supported locales with metadata
  static const List<KFLocaleInfo> supportedLocales = [
    KFLocaleInfo(
      locale: Locale('en'),
      nativeName: 'English',
      englishName: 'English',
      flag: '🇬🇧',
      targetUsers: 'Default, professionals',
    ),
    KFLocaleInfo(
      locale: Locale('ms'),
      nativeName: 'Bahasa Melayu',
      englishName: 'Malay',
      flag: '🇲🇾',
      targetUsers: 'Malaysian workers',
    ),
    KFLocaleInfo(
      locale: Locale('id'),
      nativeName: 'Bahasa Indonesia',
      englishName: 'Indonesian',
      flag: '🇮🇩',
      targetUsers: 'Indonesian workers',
    ),
    KFLocaleInfo(
      locale: Locale('zh'),
      nativeName: '简体中文',
      englishName: 'Chinese (Simplified)',
      fontFamily: 'NotoSansSC',
      flag: '🇨🇳',
      targetUsers: 'Chinese speakers',
    ),
    KFLocaleInfo(
      locale: Locale('ta'),
      nativeName: 'தமிழ்',
      englishName: 'Tamil',
      fontFamily: 'NotoSansTamil',
      flag: '🇮🇳',
      targetUsers: 'Malaysian Indians, Tamil speakers',
    ),
    KFLocaleInfo(
      locale: Locale('th'),
      nativeName: 'ภาษาไทย',
      englishName: 'Thai',
      fontFamily: 'NotoSansThai',
      flag: '🇹🇭',
      targetUsers: 'Thai workers',
    ),
    KFLocaleInfo(
      locale: Locale('vi'),
      nativeName: 'Tiếng Việt',
      englishName: 'Vietnamese',
      flag: '🇻🇳',
      targetUsers: 'Vietnamese workers',
    ),
    KFLocaleInfo(
      locale: Locale('tl'),
      nativeName: 'Filipino',
      englishName: 'Filipino/Tagalog',
      flag: '🇵🇭',
      targetUsers: 'Filipino workers',
    ),
    KFLocaleInfo(
      locale: Locale('my'),
      nativeName: 'မြန်မာဘာသာ',
      englishName: 'Myanmar (Burmese)',
      fontFamily: 'NotoSansMyanmar',
      flag: '🇲🇲',
      targetUsers: 'Myanmar workers',
    ),
    KFLocaleInfo(
      locale: Locale('km'),
      nativeName: 'ភាសាខ្មែរ',
      englishName: 'Khmer',
      fontFamily: 'NotoSansKhmer',
      flag: '🇰🇭',
      targetUsers: 'Cambodian workers',
    ),
    KFLocaleInfo(
      locale: Locale('ne'),
      nativeName: 'नेपाली',
      englishName: 'Nepali',
      fontFamily: 'NotoSansDevanagari',
      flag: '🇳🇵',
      targetUsers: 'Nepali workers',
    ),
    KFLocaleInfo(
      locale: Locale('bn'),
      nativeName: 'বাংলা',
      englishName: 'Bengali',
      fontFamily: 'NotoSansBengali',
      flag: '🇧🇩',
      targetUsers: 'Bangladeshi workers',
    ),
  ];

  /// Default fallback locale
  static const Locale fallbackLocale = Locale('en');

  /// Get all Flutter Locale objects
  static List<Locale> get locales =>
      supportedLocales.map((info) => info.locale).toList();

  /// Find locale info by language code
  static KFLocaleInfo? findByCode(String code) {
    try {
      return supportedLocales.firstWhere(
        (info) => info.locale.languageCode == code,
      );
    } catch (_) {
      return null;
    }
  }

  /// Get font family for a locale
  static String? getFontFamily(Locale locale) {
    return findByCode(locale.languageCode)?.fontFamily;
  }

  /// Check if locale needs special font
  static bool needsSpecialFont(Locale locale) {
    return getFontFamily(locale) != null;
  }

  /// Get text direction for locale
  static TextDirection getTextDirection(Locale locale) {
    return findByCode(locale.languageCode)?.direction ?? TextDirection.ltr;
  }

  /// Locale resolution callback for MaterialApp
  static Locale? localeResolutionCallback(
    Locale? locale,
    Iterable<Locale> supportedLocales,
  ) {
    if (locale == null) return fallbackLocale;

    // Find exact match
    for (final supportedLocale in supportedLocales) {
      if (supportedLocale.languageCode == locale.languageCode) {
        return supportedLocale;
      }
    }

    // Fallback to English
    return fallbackLocale;
  }
}

/// Extension for easy access to localizations from BuildContext
extension KFL10nExtension on BuildContext {
  /// Get current locale
  Locale get currentLocale => Localizations.localeOf(this);

  /// Get locale info for current locale
  KFLocaleInfo? get localeInfo =>
      KFL10n.findByCode(currentLocale.languageCode);

  /// Check if current locale needs special font
  bool get needsSpecialFont => KFL10n.needsSpecialFont(currentLocale);

  /// Get font family for current locale
  String? get localeFontFamily => KFL10n.getFontFamily(currentLocale);

  /// Get text direction for current locale
  TextDirection get localeTextDirection =>
      KFL10n.getTextDirection(currentLocale);
}

/// Widget that applies locale-aware font to its child
class KFLocalizedText extends StatelessWidget {
  final String text;
  final TextStyle? style;
  final TextAlign? textAlign;
  final int? maxLines;
  final TextOverflow? overflow;
  final bool? softWrap;

  const KFLocalizedText(
    this.text, {
    super.key,
    this.style,
    this.textAlign,
    this.maxLines,
    this.overflow,
    this.softWrap,
  });

  @override
  Widget build(BuildContext context) {
    final fontFamily = context.localeFontFamily;
    final effectiveStyle = fontFamily != null
        ? (style ?? const TextStyle()).copyWith(fontFamily: fontFamily)
        : style;

    return Text(
      text,
      style: effectiveStyle,
      textAlign: textAlign,
      maxLines: maxLines,
      overflow: overflow,
      softWrap: softWrap,
    );
  }
}

/// Builder widget that provides locale-aware theme data
class KFLocaleAwareBuilder extends StatelessWidget {
  final Widget Function(BuildContext context, TextTheme textTheme) builder;

  const KFLocaleAwareBuilder({
    super.key,
    required this.builder,
  });

  @override
  Widget build(BuildContext context) {
    final fontFamily = context.localeFontFamily;
    final baseTheme = Theme.of(context).textTheme;

    final localizedTextTheme = fontFamily != null
        ? baseTheme.apply(fontFamily: fontFamily)
        : baseTheme;

    return builder(context, localizedTextTheme);
  }
}
